# Generated by Django 3.1.7 on 2021-03-27 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Survey1',
            fields=[
                ('type_id', models.AutoField(primary_key=True, serialize=False)),
                ('covid_or_not', models.IntegerField(db_column='covid_or_not')),
            ],
            options={
                'db_table': 'survey1',
            },
        ),
    ]
